ALTER TABLE foods
ADD COLUMN nf_preview_calories_unit TEXT;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_calories_value REAL;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_fat_unit TEXT;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_fat_value REAL;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_carbs_unit TEXT;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_carbs_value REAL;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_protein_unit TEXT;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_protein_value REAL;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_fiber_unit TEXT;

--SQL-STATEMENT-SEPARATOR

ALTER TABLE foods
ADD COLUMN nf_preview_fiber_value REAL;
