// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../data/services/usda/food_usda_model.dart';
import '../data/services/usda/nutrient_usda_model.dart';
import '../data/services/usda/portion_usda_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3100248216140114974),
    name: 'NutrientUsdaModel',
    lastPropertyId: const obx_int.IdUid(7, 1752631038511398596),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4737090849343882524),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6853624155036854048),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 753847689050500645),
        name: 'number',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3834759882547384202),
        name: 'unitName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1752631038511398596),
        name: 'foodId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 2144078407591645752),
        relationTarget: 'FoodUsdaModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7621789854171293915),
    name: 'PortionUsdaModel',
    lastPropertyId: const obx_int.IdUid(5, 6322846183221195441),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5854661145337711345),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6041843963569034059),
        name: 'measureUnitId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5084490800260802718),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2330427475076862771),
        name: 'gramWeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6322846183221195441),
        name: 'foodId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8357249628330927056),
        relationTarget: 'FoodUsdaModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5397781313285217229),
    name: 'FoodUsdaModel',
    lastPropertyId: const obx_int.IdUid(4, 8197077236200161832),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5342465159471795938),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7398406017981703753),
        name: 'fdcId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 4581952073606111299),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3394316015689734521),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8197077236200161832),
        name: 'dataType',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'portions',
        srcEntity: 'PortionUsdaModel',
        srcField: 'food',
      ),
      obx_int.ModelBacklink(
        name: 'nutrients',
        srcEntity: 'NutrientUsdaModel',
        srcField: 'food',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 5397781313285217229),
    lastIndexId: const obx_int.IdUid(3, 4581952073606111299),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [2320777525505843762, 4414707025892638220],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NutrientUsdaModel: obx_int.EntityDefinition<NutrientUsdaModel>(
      model: _entities[0],
      toOneRelations: (NutrientUsdaModel object) => [object.food],
      toManyRelations: (NutrientUsdaModel object) => {},
      getId: (NutrientUsdaModel object) => object.id,
      setId: (NutrientUsdaModel object, int id) {
        object.id = id;
      },
      objectToFB: (NutrientUsdaModel object, fb.Builder fbb) {
        final numberOffset = fbb.writeString(object.number);
        final unitNameOffset = fbb.writeString(object.unitName);
        fbb.startTable(8);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(4, numberOffset);
        fbb.addOffset(5, unitNameOffset);
        fbb.addInt64(6, object.food.targetId);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final unitNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = NutrientUsdaModel(
          id: idParam,
          number: numberParam,
          amount: amountParam,
          unitName: unitNameParam,
        );
        object.food.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.food.attach(store);
        return object;
      },
    ),
    PortionUsdaModel: obx_int.EntityDefinition<PortionUsdaModel>(
      model: _entities[1],
      toOneRelations: (PortionUsdaModel object) => [object.food],
      toManyRelations: (PortionUsdaModel object) => {},
      getId: (PortionUsdaModel object) => object.id,
      setId: (PortionUsdaModel object, int id) {
        object.id = id;
      },
      objectToFB: (PortionUsdaModel object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addInt64(1, object.measureUnitId);
        fbb.addFloat64(2, object.amount);
        fbb.addFloat64(3, object.gramWeight);
        fbb.addInt64(4, object.food.targetId);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final measureUnitIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final gramWeightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = PortionUsdaModel(
          id: idParam,
          measureUnitId: measureUnitIdParam,
          amount: amountParam,
          gramWeight: gramWeightParam,
        );
        object.food.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.food.attach(store);
        return object;
      },
    ),
    FoodUsdaModel: obx_int.EntityDefinition<FoodUsdaModel>(
      model: _entities[2],
      toOneRelations: (FoodUsdaModel object) => [],
      toManyRelations: (FoodUsdaModel object) => {
        obx_int.RelInfo<PortionUsdaModel>.toOneBacklink(
          5,
          object.id!,
          (PortionUsdaModel srcObject) => srcObject.food,
        ): object.portions,
        obx_int.RelInfo<NutrientUsdaModel>.toOneBacklink(
          7,
          object.id!,
          (NutrientUsdaModel srcObject) => srcObject.food,
        ): object.nutrients,
      },
      getId: (FoodUsdaModel object) => object.id,
      setId: (FoodUsdaModel object, int id) {
        object.id = id;
      },
      objectToFB: (FoodUsdaModel object, fb.Builder fbb) {
        final descriptionOffset = fbb.writeString(object.description);
        final dataTypeOffset = fbb.writeString(object.dataType);
        fbb.startTable(5);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addInt64(1, object.fdcId);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, dataTypeOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final fdcIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dataTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = FoodUsdaModel(
          id: idParam,
          fdcId: fdcIdParam,
          description: descriptionParam,
          dataType: dataTypeParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<FoodUsdaModel>(
          object.portions,
          store,
          obx_int.RelInfo<PortionUsdaModel>.toOneBacklink(
            5,
            object.id!,
            (PortionUsdaModel srcObject) => srcObject.food,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<FoodUsdaModel>(
          object.nutrients,
          store,
          obx_int.RelInfo<NutrientUsdaModel>.toOneBacklink(
            7,
            object.id!,
            (NutrientUsdaModel srcObject) => srcObject.food,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NutrientUsdaModel] entity fields to define ObjectBox queries.
class NutrientUsdaModel_ {
  /// See [NutrientUsdaModel.id].
  static final id = obx.QueryIntegerProperty<NutrientUsdaModel>(
    _entities[0].properties[0],
  );

  /// See [NutrientUsdaModel.amount].
  static final amount = obx.QueryDoubleProperty<NutrientUsdaModel>(
    _entities[0].properties[1],
  );

  /// See [NutrientUsdaModel.number].
  static final number = obx.QueryStringProperty<NutrientUsdaModel>(
    _entities[0].properties[2],
  );

  /// See [NutrientUsdaModel.unitName].
  static final unitName = obx.QueryStringProperty<NutrientUsdaModel>(
    _entities[0].properties[3],
  );

  /// See [NutrientUsdaModel.food].
  static final food = obx.QueryRelationToOne<NutrientUsdaModel, FoodUsdaModel>(
    _entities[0].properties[4],
  );
}

/// [PortionUsdaModel] entity fields to define ObjectBox queries.
class PortionUsdaModel_ {
  /// See [PortionUsdaModel.id].
  static final id = obx.QueryIntegerProperty<PortionUsdaModel>(
    _entities[1].properties[0],
  );

  /// See [PortionUsdaModel.measureUnitId].
  static final measureUnitId = obx.QueryIntegerProperty<PortionUsdaModel>(
    _entities[1].properties[1],
  );

  /// See [PortionUsdaModel.amount].
  static final amount = obx.QueryDoubleProperty<PortionUsdaModel>(
    _entities[1].properties[2],
  );

  /// See [PortionUsdaModel.gramWeight].
  static final gramWeight = obx.QueryDoubleProperty<PortionUsdaModel>(
    _entities[1].properties[3],
  );

  /// See [PortionUsdaModel.food].
  static final food = obx.QueryRelationToOne<PortionUsdaModel, FoodUsdaModel>(
    _entities[1].properties[4],
  );
}

/// [FoodUsdaModel] entity fields to define ObjectBox queries.
class FoodUsdaModel_ {
  /// See [FoodUsdaModel.id].
  static final id = obx.QueryIntegerProperty<FoodUsdaModel>(
    _entities[2].properties[0],
  );

  /// See [FoodUsdaModel.fdcId].
  static final fdcId = obx.QueryIntegerProperty<FoodUsdaModel>(
    _entities[2].properties[1],
  );

  /// See [FoodUsdaModel.description].
  static final description = obx.QueryStringProperty<FoodUsdaModel>(
    _entities[2].properties[2],
  );

  /// See [FoodUsdaModel.dataType].
  static final dataType = obx.QueryStringProperty<FoodUsdaModel>(
    _entities[2].properties[3],
  );

  /// see [FoodUsdaModel.portions]
  static final portions =
      obx.QueryBacklinkToMany<PortionUsdaModel, FoodUsdaModel>(
        PortionUsdaModel_.food,
      );

  /// see [FoodUsdaModel.nutrients]
  static final nutrients =
      obx.QueryBacklinkToMany<NutrientUsdaModel, FoodUsdaModel>(
        NutrientUsdaModel_.food,
      );
}
