@startuml

'!pragma useVerticalIf on

title Import Activity Diagram

start
floating note left: The process is triggered by successful login

:var importRecord = await bookImport(); <<procedure>>

if (UnresolvedImportException) then (yes)
  -[#red]->
  :importRecord = error.importReport;
else (no)
  -[#blue]->
endif

if (importRecord == null) then (yes)
  end
(no) elseif (importRecord.deviceId != currentDeviceId) then (yes)
  :
  show screen
  **unresloved import from another device**
  ; <<output>>

  :action; <<input>>

  switch (action)
    case (contact support)
      :
      open
      **email client**
      with
      - to: support email address
      - subject: Import issue
      - body: ...currentDeviceId...
      ;
      end
    case (logout)
      :logout;
      end
  endswitch
else (no)
  #green:(A)
  
  switch (importRecord.currentState)
    case (booked)
      :
      show screen
      **import confirmation**
      ; <<output>>

      :action; <<input>>

      switch (action)
        case (confirm import)
          group try {
            :
            importRecord.states.add(
              ImportStateRecord(
                state: ImportState.inProgress,
                at: DateTime.now(),
              ),
            )
            ;

            :
            **firestore**
            save importRecord
            ; <<save>>

            :
            **firestore**
            purge data
            ; <<save>>

            :
            **firestore**
            import local data
            ; <<save>>

            :
            importRecord.states.add(
              ImportStateRecord(
                state: ImportState.succeeded,
                at: DateTime.now(),
              ),
            )
            ;

            :
            **firestore**
            save importRecord
            ; <<save>>
          }

          if (error) then (yes)
            -[#red]->
            :
            importRecord.states.add(
              ImportStateRecord(
                state: ImportState.failed,
                at: DateTime.now(),
              ),
            )
            ;

            :
            **firestore**
            save importRecord
            ; <<save>>
          else (no)
            -[#blue]->
          endif

          #green:(A)
          kill
        case (decline import)
          :
          importRecord.states.add(
            ImportStateRecord(
              state: ImportState.declined,
              at: DateTime.now(),
            ),
          )
          ;

          :
          **firestore**
          save importRecord
          ; <<save>>
      endswitch
    case (inProgress | failed)
      :
      show screen
      **unresloved import from this device**
      ; <<output>>

      :action; <<input>>

      switch (action)
        case (cleanup and retry)
          :
          **firestore**
          purge data
          ; <<save>>

          :
          importRecord.states.add(
            ImportStateRecord(
              state: ImportState.booked,
              at: DateTime.now(),
            ),
          )
          ;

          :
          **firestore**
          save importRecord
          ; <<save>>

          #green:(A)
          kill
        case (cleanup and proceed)
          :
          **firestore**
          purge data
          ; <<save>>

          :
          importRecord.states.add(
            ImportStateRecord(
              state: ImportState.reverted,
              at: DateTime.now(),
            ),
          )
          ;

          :
          **firestore**
          save importRecord
          ; <<save>>
        case (ignore and proceed)
          :
          importRecord.states.add(
            ImportStateRecord(
              state: ImportState.ignored,
              at: DateTime.now(),
            ),
          )
          ;

          :
          **firestore**
          save importRecord
          ; <<save>>
      endswitch
    case (succeeded)
      :
      show screen
      **import success**
      ; <<output>>

      :
      importRecord.states.add(
        ImportStateRecord(
          state: ImportState.acknowledged,
          at: DateTime.now(),
        ),
      )
      ;

      :
      **firestore**
      save importRecord
      ; <<save>>
    case (otherwise)
  endswitch
endif

end

:Future<ImportRecord?> bookImport(); <<procedure>>
if (
  is **local DB** empty
) then (yes)
  :null; <<output>>
  kill
else (no)
  group Firestore transaction {
    :
    **firestore**
    get import records into
    var importRecords
    ; <<load>>

    if (
      importRecords.isEmpty
    ) then (yes)
    else (no)
      :
      var unresolvedImportRecords = importRecords.where(
        (i) => !i.resolved,
      )
      ;

      :
      var unresolvedImportRecordsFromOtherDevices = unresolvedImportRecords.where(
        (i) => i.deviceId != **currentDeviceId**,
      ).toList()
      ;

      :
      var unresolvedImportRecordsFromThisDevice = unresolvedImportRecords.where(
        (i) => i.deviceId == **currentDeviceId**,
      ).toList()
      ;

      :
      var resolvedImportRecordFromThisDeviceExists = importRecords.any(
        (i) => (
          i.deviceId == **currentDeviceId**
          && i.resolved
        ),
      )
      ;

      if (
        unresolvedImportRecordsFromOtherDevices.isNotEmpty
      ) then (yes)
        #red:
        **throw**
        UnresolvedImportException(
          unresolvedImportRecordsFromOtherDevices.first
        )
        ;
        kill
      (no) elseif (
        unresolvedImportRecordsFromThisDevice.isNotEmpty
      ) then (yes)
        #red:
        **throw**
        UnresolvedImportException(
          unresolvedImportRecordsFromThisDevice.first
        )
        ;
        kill
      (no) elseif (
        resolvedImportRecordFromThisDeviceExists
      ) then (yes)
        :null; <<output>>
        kill
      else (no)
      endif
    endif

    if (
      is **firestore** empty
    ) then (yes)
      :
      var importRecord = ImportRecord(
        deviceId: currentDeviceId,
        states: [
          ImportStateRecord(
            state: ImportState.booked,
            at: DateTime.now(),
          ),
        ],
      )
      ;

      :
      **firestore**
      add importRecord
      ; <<save>>

      :importRecord; <<output>>
      kill
    else (no)
      :null; <<output>>
      kill
    endif
  }
endif

@enduml


